analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20 # Максимальная допустимая сложность
    lines-of-code: 50 # Максимальное количество строк в методе
  rules:
    - avoid-global-state